-- =========================================================
-- FINTECH REBUILD - STEP 2
-- Staff authorization foundation + audit logging
-- Run AFTER Step 1 foundation is working.
-- =========================================================

begin;

-- Keep authorization helper functions outside the exposed public schema.
create schema if not exists private;
revoke all on schema private from public;
grant usage on schema private to authenticated;

create or replace function private.current_app_role()
returns public.app_role
language sql
stable
security definer
set search_path = ''
as $$
  select p.role
  from public.profiles p
  where p.id = (select auth.uid())
    and p.status = 'active'::public.profile_status
  limit 1;
$$;

create or replace function private.is_active_user()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = (select auth.uid())
      and p.status = 'active'::public.profile_status
  );
$$;

create or replace function private.can_manage_staff()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(
    private.current_app_role() = any (
      array['super_admin', 'admin']::public.app_role[]
    ),
    false
  );
$$;

create or replace function private.can_view_audit()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(
    private.current_app_role() = any (
      array['super_admin', 'admin', 'auditor']::public.app_role[]
    ),
    false
  );
$$;

revoke all on function private.current_app_role() from public;
revoke all on function private.is_active_user() from public;
revoke all on function private.can_manage_staff() from public;
revoke all on function private.can_view_audit() from public;

grant execute on function private.current_app_role() to authenticated;
grant execute on function private.is_active_user() to authenticated;
grant execute on function private.can_manage_staff() to authenticated;
grant execute on function private.can_view_audit() to authenticated;

-- Immutable application audit trail.
create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid references public.profiles(id) on delete set null,
  actor_name text,
  actor_email text,
  action text not null,
  entity_type text not null,
  entity_id uuid,
  description text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists audit_logs_created_at_idx
  on public.audit_logs (created_at desc);

create index if not exists audit_logs_actor_id_idx
  on public.audit_logs (actor_id);

create index if not exists audit_logs_entity_idx
  on public.audit_logs (entity_type, entity_id);

alter table public.audit_logs enable row level security;

-- No browser-side writes to audit history.
revoke all on table public.audit_logs from anon;
revoke all on table public.audit_logs from authenticated;
grant select on table public.audit_logs to authenticated;

-- Identity sequence privileges can otherwise leak through broad grants.
revoke all on sequence public.audit_logs_id_seq from anon;
revoke all on sequence public.audit_logs_id_seq from authenticated;

-- Only trusted roles may view the audit trail.
drop policy if exists "authorized roles can view audit logs"
  on public.audit_logs;

create policy "authorized roles can view audit logs"
on public.audit_logs
for select
to authenticated
using ((select private.can_view_audit()));

commit;
