-- =========================================================
-- FINTECH REBUILD - STEP 4
-- Financial ledger + deposits + withdrawals + approvals
-- Run AFTER:
--   004_staff_authorization_audit.sql
--   005_customers_accounts.sql
--   006_three_digit_customer_numbers.sql (if you used the patch)
-- =========================================================

begin;

-- ---------------------------------------------------------
-- 1. ENUMS
-- ---------------------------------------------------------

do $$
begin
  if not exists (
    select 1
    from pg_type t
    join pg_namespace n on n.oid = t.typnamespace
    where t.typname = 'transaction_type'
      and n.nspname = 'public'
  ) then
    create type public.transaction_type as enum (
      'deposit',
      'withdrawal',
      'reversal'
    );
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_type t
    join pg_namespace n on n.oid = t.typnamespace
    where t.typname = 'transaction_status'
      and n.nspname = 'public'
  ) then
    create type public.transaction_status as enum (
      'pending',
      'approved',
      'rejected',
      'reversed'
    );
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_type t
    join pg_namespace n on n.oid = t.typnamespace
    where t.typname = 'ledger_direction'
      and n.nspname = 'public'
  ) then
    create type public.ledger_direction as enum (
      'credit',
      'debit'
    );
  end if;
end
$$;

-- ---------------------------------------------------------
-- 2. TRANSACTION REFERENCE SEQUENCE
-- ---------------------------------------------------------

create sequence if not exists public.transaction_reference_seq
  start with 1
  increment by 1;

revoke all on sequence public.transaction_reference_seq from anon, authenticated;

-- ---------------------------------------------------------
-- 3. TRANSACTIONS + IMMUTABLE LEDGER
-- ---------------------------------------------------------

create table if not exists public.transactions (
  id uuid primary key default gen_random_uuid(),
  reference text not null unique,
  customer_id uuid not null references public.customers(id) on delete restrict,
  account_id uuid not null references public.accounts(id) on delete restrict,
  type public.transaction_type not null,
  amount_minor bigint not null,
  status public.transaction_status not null default 'pending',
  description text,
  rejection_reason text,

  initiated_by uuid not null references public.profiles(id) on delete restrict,
  initiated_by_name text not null,
  initiated_at timestamptz not null default now(),

  reviewed_by uuid references public.profiles(id) on delete restrict,
  reviewed_by_name text,
  reviewed_at timestamptz,

  reversal_of uuid references public.transactions(id) on delete restrict,
  reversed_by_transaction_id uuid references public.transactions(id) on delete restrict,

  created_at timestamptz not null default now(),

  constraint transactions_amount_positive check (amount_minor > 0),
  constraint transactions_reversal_shape check (
    (type = 'reversal'::public.transaction_type and reversal_of is not null)
    or
    (type <> 'reversal'::public.transaction_type and reversal_of is null)
  )
);

create table if not exists public.ledger_entries (
  id bigint generated by default as identity primary key,
  transaction_id uuid not null unique references public.transactions(id) on delete restrict,
  account_id uuid not null references public.accounts(id) on delete restrict,
  direction public.ledger_direction not null,
  amount_minor bigint not null,
  balance_before_minor bigint not null,
  balance_after_minor bigint not null,
  posted_by uuid not null references public.profiles(id) on delete restrict,
  created_at timestamptz not null default now(),

  constraint ledger_amount_positive check (amount_minor > 0)
);

create index if not exists transactions_created_at_idx
  on public.transactions (created_at desc);

create index if not exists transactions_status_created_at_idx
  on public.transactions (status, created_at desc);

create index if not exists transactions_account_id_created_at_idx
  on public.transactions (account_id, created_at desc);

create index if not exists transactions_customer_id_created_at_idx
  on public.transactions (customer_id, created_at desc);

create index if not exists transactions_initiated_by_idx
  on public.transactions (initiated_by);

create index if not exists transactions_reversal_of_idx
  on public.transactions (reversal_of);

create index if not exists ledger_entries_account_id_created_at_idx
  on public.ledger_entries (account_id, created_at desc);

-- ---------------------------------------------------------
-- 4. AUTHORIZATION HELPERS
-- ---------------------------------------------------------

create or replace function private.can_initiate_transactions()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(
    private.current_app_role() = any (
      array['super_admin', 'admin', 'manager', 'staff']::public.app_role[]
    ),
    false
  );
$$;

create or replace function private.can_approve_transactions()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(
    private.current_app_role() = any (
      array['super_admin', 'admin', 'manager']::public.app_role[]
    ),
    false
  );
$$;

create or replace function private.can_request_reversal()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(
    private.current_app_role() = any (
      array['super_admin', 'admin']::public.app_role[]
    ),
    false
  );
$$;

revoke all on function private.can_initiate_transactions() from public;
revoke all on function private.can_approve_transactions() from public;
revoke all on function private.can_request_reversal() from public;

grant execute on function private.can_initiate_transactions() to authenticated;
grant execute on function private.can_approve_transactions() to authenticated;
grant execute on function private.can_request_reversal() to authenticated;

-- ---------------------------------------------------------
-- 5. INTERNAL HELPERS
-- ---------------------------------------------------------

create or replace function private.next_transaction_reference()
returns text
language sql
volatile
security definer
set search_path = ''
as $$
  select 'TXN' || lpad(nextval('public.transaction_reference_seq')::text, 8, '0');
$$;

create or replace function private.current_actor_name()
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(nullif(btrim(p.full_name), ''), 'Staff')
  from public.profiles p
  where p.id = (select auth.uid())
  limit 1;
$$;

revoke all on function private.next_transaction_reference() from public;
revoke all on function private.current_actor_name() from public;

-- ---------------------------------------------------------
-- 6. RLS + PRIVILEGES
-- ---------------------------------------------------------

alter table public.transactions enable row level security;
alter table public.ledger_entries enable row level security;

revoke all on table public.transactions from anon, authenticated;
revoke all on table public.ledger_entries from anon, authenticated;

grant select on table public.transactions to authenticated;
grant select on table public.ledger_entries to authenticated;

revoke all on sequence public.ledger_entries_id_seq from anon, authenticated;

drop policy if exists "active staff can view transactions" on public.transactions;
create policy "active staff can view transactions"
on public.transactions
for select
to authenticated
using ((select private.is_active_user()));

drop policy if exists "active staff can view ledger entries" on public.ledger_entries;
create policy "active staff can view ledger entries"
on public.ledger_entries
for select
to authenticated
using ((select private.is_active_user()));

-- ---------------------------------------------------------
-- 7. SAFE TRANSACTION DIRECTORY VIEW
-- security_invoker makes the view obey underlying RLS.
-- ---------------------------------------------------------

create or replace view public.transaction_directory
with (security_invoker = true)
as
select
  t.id,
  t.reference,
  t.type,
  t.amount_minor,
  t.status,
  t.description,
  t.rejection_reason,
  t.initiated_by,
  t.initiated_by_name,
  t.initiated_at,
  t.reviewed_by,
  t.reviewed_by_name,
  t.reviewed_at,
  t.reversal_of,
  t.reversed_by_transaction_id,
  t.created_at,

  a.id as account_id,
  a.account_number,
  a.account_type,
  a.currency,
  a.status as account_status,
  a.cached_balance_minor as account_balance_minor,

  c.id as customer_id,
  c.customer_number,
  concat_ws(' ', c.first_name, nullif(c.middle_name, ''), c.last_name) as customer_name,
  c.status as customer_status,

  original.reference as original_reference

from public.transactions t
join public.accounts a on a.id = t.account_id
join public.customers c on c.id = t.customer_id
left join public.transactions original on original.id = t.reversal_of;

revoke all on table public.transaction_directory from anon, authenticated;
grant select on table public.transaction_directory to authenticated;

-- ---------------------------------------------------------
-- 8. INITIATE DEPOSIT / WITHDRAWAL
-- No account balance is changed here.
-- ---------------------------------------------------------

create or replace function public.initiate_transaction(
  p_account_id uuid,
  p_type public.transaction_type,
  p_amount_minor bigint,
  p_description text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor_id uuid := auth.uid();
  v_actor_name text;
  v_account public.accounts;
  v_customer public.customers;
  v_transaction public.transactions;
begin
  if v_actor_id is null or not private.can_initiate_transactions() then
    raise exception 'You do not have permission to initiate transactions.'
      using errcode = '42501';
  end if;

  if p_type not in (
    'deposit'::public.transaction_type,
    'withdrawal'::public.transaction_type
  ) then
    raise exception 'Only deposits and withdrawals can be initiated directly.'
      using errcode = '22023';
  end if;

  if p_amount_minor is null or p_amount_minor <= 0 then
    raise exception 'Transaction amount must be greater than zero.'
      using errcode = '22023';
  end if;

  select * into v_account
  from public.accounts a
  where a.id = p_account_id;

  if not found then
    raise exception 'Account not found.' using errcode = 'P0002';
  end if;

  if v_account.status <> 'active'::public.account_status then
    raise exception 'Only active accounts can receive new transactions.'
      using errcode = '22023';
  end if;

  select * into v_customer
  from public.customers c
  where c.id = v_account.customer_id;

  if v_customer.status <> 'active'::public.customer_status then
    raise exception 'Only active customers can receive new transactions.'
      using errcode = '22023';
  end if;

  -- Early validation for withdrawals. This is checked again under
  -- row lock during approval to protect against concurrent activity.
  if p_type = 'withdrawal'::public.transaction_type
     and v_account.cached_balance_minor < p_amount_minor then
    raise exception 'Insufficient account balance for this withdrawal.'
      using errcode = '22003';
  end if;

  v_actor_name := private.current_actor_name();

  insert into public.transactions (
    reference,
    customer_id,
    account_id,
    type,
    amount_minor,
    status,
    description,
    initiated_by,
    initiated_by_name
  ) values (
    private.next_transaction_reference(),
    v_customer.id,
    v_account.id,
    p_type,
    p_amount_minor,
    'pending'::public.transaction_status,
    nullif(btrim(coalesce(p_description, '')), ''),
    v_actor_id,
    v_actor_name
  )
  returning * into v_transaction;

  insert into public.audit_logs (
    actor_id,
    actor_name,
    actor_email,
    action,
    entity_type,
    entity_id,
    description,
    metadata
  )
  values (
    v_actor_id,
    v_actor_name,
    private.current_actor_email(),
    'transaction.initiated',
    'transaction',
    v_transaction.id,
    'Initiated ' || v_transaction.type::text || ' ' || v_transaction.reference || '.',
    jsonb_build_object(
      'reference', v_transaction.reference,
      'customer_number', v_customer.customer_number,
      'account_number', v_account.account_number,
      'type', v_transaction.type,
      'amount_minor', v_transaction.amount_minor
    )
  );

  return to_jsonb(v_transaction);
end;
$$;

-- ---------------------------------------------------------
-- 9. REQUEST REVERSAL
-- Reversals are also maker-checker: request first, then another
-- eligible admin approves it.
-- ---------------------------------------------------------

create or replace function public.request_transaction_reversal(
  p_transaction_id uuid,
  p_reason text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor_id uuid := auth.uid();
  v_actor_name text;
  v_original public.transactions;
  v_reversal public.transactions;
  v_reason text := nullif(btrim(coalesce(p_reason, '')), '');
begin
  if v_actor_id is null or not private.can_request_reversal() then
    raise exception 'You do not have permission to request transaction reversals.'
      using errcode = '42501';
  end if;

  if v_reason is null then
    raise exception 'A reversal reason is required.' using errcode = '22023';
  end if;

  select * into v_original
  from public.transactions t
  where t.id = p_transaction_id
  for update;

  if not found then
    raise exception 'Transaction not found.' using errcode = 'P0002';
  end if;

  if v_original.type = 'reversal'::public.transaction_type then
    raise exception 'A reversal transaction cannot itself be reversed in Step 4.'
      using errcode = '22023';
  end if;

  if v_original.status <> 'approved'::public.transaction_status then
    raise exception 'Only approved transactions can be reversed.'
      using errcode = '22023';
  end if;

  if v_original.reversed_by_transaction_id is not null then
    raise exception 'This transaction has already been reversed.'
      using errcode = '23505';
  end if;

  if exists (
    select 1
    from public.transactions r
    where r.reversal_of = v_original.id
      and r.status = 'pending'::public.transaction_status
  ) then
    raise exception 'A reversal request is already pending for this transaction.'
      using errcode = '23505';
  end if;

  v_actor_name := private.current_actor_name();

  insert into public.transactions (
    reference,
    customer_id,
    account_id,
    type,
    amount_minor,
    status,
    description,
    initiated_by,
    initiated_by_name,
    reversal_of
  ) values (
    private.next_transaction_reference(),
    v_original.customer_id,
    v_original.account_id,
    'reversal'::public.transaction_type,
    v_original.amount_minor,
    'pending'::public.transaction_status,
    v_reason,
    v_actor_id,
    v_actor_name,
    v_original.id
  )
  returning * into v_reversal;

  insert into public.audit_logs (
    actor_id,
    actor_name,
    actor_email,
    action,
    entity_type,
    entity_id,
    description,
    metadata
  )
  values (
    v_actor_id,
    v_actor_name,
    private.current_actor_email(),
    'transaction.reversal_requested',
    'transaction',
    v_reversal.id,
    'Requested reversal ' || v_reversal.reference || ' for ' || v_original.reference || '.',
    jsonb_build_object(
      'reversal_reference', v_reversal.reference,
      'original_reference', v_original.reference,
      'reason', v_reason
    )
  );

  return to_jsonb(v_reversal);
end;
$$;

-- ---------------------------------------------------------
-- 10. APPROVE TRANSACTION AND POST LEDGER ENTRY ATOMICALLY
-- ---------------------------------------------------------

create or replace function public.approve_transaction(
  p_transaction_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor_id uuid := auth.uid();
  v_actor_name text;
  v_actor_role public.app_role;
  v_transaction public.transactions;
  v_original public.transactions;
  v_account public.accounts;
  v_customer public.customers;
  v_balance_before bigint;
  v_balance_after bigint;
  v_direction public.ledger_direction;
  v_delta bigint;
  v_updated public.transactions;
begin
  if v_actor_id is null or not private.can_approve_transactions() then
    raise exception 'You do not have permission to approve transactions.'
      using errcode = '42501';
  end if;

  v_actor_role := private.current_app_role();
  v_actor_name := private.current_actor_name();

  select * into v_transaction
  from public.transactions t
  where t.id = p_transaction_id
  for update;

  if not found then
    raise exception 'Transaction not found.' using errcode = 'P0002';
  end if;

  if v_transaction.status <> 'pending'::public.transaction_status then
    raise exception 'Only pending transactions can be approved.'
      using errcode = '22023';
  end if;

  if v_transaction.initiated_by = v_actor_id then
    raise exception 'Maker-checker protection: you cannot approve your own transaction.'
      using errcode = '42501';
  end if;

  if v_transaction.type = 'reversal'::public.transaction_type
     and v_actor_role not in ('super_admin'::public.app_role, 'admin'::public.app_role) then
    raise exception 'Only an administrator can approve a reversal.'
      using errcode = '42501';
  end if;

  select * into v_account
  from public.accounts a
  where a.id = v_transaction.account_id
  for update;

  if not found then
    raise exception 'Account not found.' using errcode = 'P0002';
  end if;

  select * into v_customer
  from public.customers c
  where c.id = v_transaction.customer_id;

  v_balance_before := v_account.cached_balance_minor;

  if v_transaction.type = 'deposit'::public.transaction_type then
    if v_account.status <> 'active'::public.account_status
       or v_customer.status <> 'active'::public.customer_status then
      raise exception 'The customer and account must both be active before approval.'
        using errcode = '22023';
    end if;

    v_delta := v_transaction.amount_minor;
    v_direction := 'credit'::public.ledger_direction;

  elsif v_transaction.type = 'withdrawal'::public.transaction_type then
    if v_account.status <> 'active'::public.account_status
       or v_customer.status <> 'active'::public.customer_status then
      raise exception 'The customer and account must both be active before approval.'
        using errcode = '22023';
    end if;

    if v_balance_before < v_transaction.amount_minor then
      raise exception 'Insufficient account balance at approval time.'
        using errcode = '22003';
    end if;

    v_delta := -v_transaction.amount_minor;
    v_direction := 'debit'::public.ledger_direction;

  else
    -- Reversal: lock and validate the original approved transaction.
    select * into v_original
    from public.transactions t
    where t.id = v_transaction.reversal_of
    for update;

    if not found then
      raise exception 'Original transaction for this reversal was not found.'
        using errcode = 'P0002';
    end if;

    if v_original.status <> 'approved'::public.transaction_status
       or v_original.reversed_by_transaction_id is not null then
      raise exception 'The original transaction is no longer eligible for reversal.'
        using errcode = '22023';
    end if;

    if v_original.type = 'deposit'::public.transaction_type then
      if v_balance_before < v_transaction.amount_minor then
        raise exception 'The deposit cannot be reversed because the account no longer has sufficient funds.'
          using errcode = '22003';
      end if;

      v_delta := -v_transaction.amount_minor;
      v_direction := 'debit'::public.ledger_direction;

    elsif v_original.type = 'withdrawal'::public.transaction_type then
      v_delta := v_transaction.amount_minor;
      v_direction := 'credit'::public.ledger_direction;

    else
      raise exception 'Unsupported original transaction type for reversal.'
        using errcode = '22023';
    end if;
  end if;

  v_balance_after := v_balance_before + v_delta;

  update public.accounts
  set
    cached_balance_minor = v_balance_after,
    updated_at = now()
  where id = v_account.id;

  insert into public.ledger_entries (
    transaction_id,
    account_id,
    direction,
    amount_minor,
    balance_before_minor,
    balance_after_minor,
    posted_by
  ) values (
    v_transaction.id,
    v_account.id,
    v_direction,
    v_transaction.amount_minor,
    v_balance_before,
    v_balance_after,
    v_actor_id
  );

  update public.transactions
  set
    status = 'approved'::public.transaction_status,
    reviewed_by = v_actor_id,
    reviewed_by_name = v_actor_name,
    reviewed_at = now()
  where id = v_transaction.id
  returning * into v_updated;

  if v_transaction.type = 'reversal'::public.transaction_type then
    update public.transactions
    set
      status = 'reversed'::public.transaction_status,
      reversed_by_transaction_id = v_transaction.id
    where id = v_original.id;
  end if;

  insert into public.audit_logs (
    actor_id,
    actor_name,
    actor_email,
    action,
    entity_type,
    entity_id,
    description,
    metadata
  )
  values (
    v_actor_id,
    v_actor_name,
    private.current_actor_email(),
    case
      when v_transaction.type = 'reversal'::public.transaction_type
        then 'transaction.reversal_approved'
      else 'transaction.approved'
    end,
    'transaction',
    v_updated.id,
    'Approved ' || v_updated.type::text || ' ' || v_updated.reference || '.',
    jsonb_build_object(
      'reference', v_updated.reference,
      'type', v_updated.type,
      'amount_minor', v_updated.amount_minor,
      'balance_before_minor', v_balance_before,
      'balance_after_minor', v_balance_after,
      'original_transaction_id', v_updated.reversal_of
    )
  );

  return jsonb_build_object(
    'transaction', to_jsonb(v_updated),
    'balance_before_minor', v_balance_before,
    'balance_after_minor', v_balance_after
  );
end;
$$;

-- ---------------------------------------------------------
-- 11. REJECT PENDING TRANSACTION
-- ---------------------------------------------------------

create or replace function public.reject_transaction(
  p_transaction_id uuid,
  p_reason text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor_id uuid := auth.uid();
  v_actor_name text;
  v_actor_role public.app_role;
  v_transaction public.transactions;
  v_updated public.transactions;
  v_reason text := nullif(btrim(coalesce(p_reason, '')), '');
begin
  if v_actor_id is null or not private.can_approve_transactions() then
    raise exception 'You do not have permission to reject transactions.'
      using errcode = '42501';
  end if;

  if v_reason is null then
    raise exception 'A rejection reason is required.' using errcode = '22023';
  end if;

  v_actor_role := private.current_app_role();
  v_actor_name := private.current_actor_name();

  select * into v_transaction
  from public.transactions t
  where t.id = p_transaction_id
  for update;

  if not found then
    raise exception 'Transaction not found.' using errcode = 'P0002';
  end if;

  if v_transaction.status <> 'pending'::public.transaction_status then
    raise exception 'Only pending transactions can be rejected.'
      using errcode = '22023';
  end if;

  if v_transaction.initiated_by = v_actor_id then
    raise exception 'Maker-checker protection: you cannot reject your own transaction.'
      using errcode = '42501';
  end if;

  if v_transaction.type = 'reversal'::public.transaction_type
     and v_actor_role not in ('super_admin'::public.app_role, 'admin'::public.app_role) then
    raise exception 'Only an administrator can reject a reversal.'
      using errcode = '42501';
  end if;

  update public.transactions
  set
    status = 'rejected'::public.transaction_status,
    rejection_reason = v_reason,
    reviewed_by = v_actor_id,
    reviewed_by_name = v_actor_name,
    reviewed_at = now()
  where id = v_transaction.id
  returning * into v_updated;

  insert into public.audit_logs (
    actor_id,
    actor_name,
    actor_email,
    action,
    entity_type,
    entity_id,
    description,
    metadata
  )
  values (
    v_actor_id,
    v_actor_name,
    private.current_actor_email(),
    'transaction.rejected',
    'transaction',
    v_updated.id,
    'Rejected ' || v_updated.reference || '.',
    jsonb_build_object(
      'reference', v_updated.reference,
      'type', v_updated.type,
      'amount_minor', v_updated.amount_minor,
      'reason', v_reason
    )
  );

  return to_jsonb(v_updated);
end;
$$;

-- ---------------------------------------------------------
-- 12. SUMMARY
-- ---------------------------------------------------------

create or replace function public.get_transaction_summary()
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select case
    when private.is_active_user() then
      jsonb_build_object(
        'pending_count',
          count(*) filter (
            where t.status = 'pending'::public.transaction_status
          ),
        'approved_today_count',
          count(*) filter (
            where t.status = 'approved'::public.transaction_status
              and t.reviewed_at >= date_trunc('day', now())
          ),
        'deposits_today_minor',
          coalesce(sum(t.amount_minor) filter (
            where t.type = 'deposit'::public.transaction_type
              and t.status = 'approved'::public.transaction_status
              and t.reviewed_at >= date_trunc('day', now())
          ), 0),
        'withdrawals_today_minor',
          coalesce(sum(t.amount_minor) filter (
            where t.type = 'withdrawal'::public.transaction_type
              and t.status = 'approved'::public.transaction_status
              and t.reviewed_at >= date_trunc('day', now())
          ), 0)
      )
    else
      null
  end
  from public.transactions t;
$$;

-- ---------------------------------------------------------
-- 13. IMMUTABLE LEDGER GUARD
-- ---------------------------------------------------------

create or replace function private.prevent_ledger_mutation()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  raise exception 'Ledger entries are immutable. Post a compensating transaction instead.'
    using errcode = '42501';
end;
$$;

drop trigger if exists ledger_entries_immutable
  on public.ledger_entries;

create trigger ledger_entries_immutable
before update or delete on public.ledger_entries
for each row
execute function private.prevent_ledger_mutation();

-- ---------------------------------------------------------
-- 14. FUNCTION PRIVILEGES
-- ---------------------------------------------------------

revoke execute on function public.initiate_transaction(
  uuid, public.transaction_type, bigint, text
) from public, anon;

revoke execute on function public.request_transaction_reversal(
  uuid, text
) from public, anon;

revoke execute on function public.approve_transaction(
  uuid
) from public, anon;

revoke execute on function public.reject_transaction(
  uuid, text
) from public, anon;

revoke execute on function public.get_transaction_summary()
from public, anon;

grant execute on function public.initiate_transaction(
  uuid, public.transaction_type, bigint, text
) to authenticated;

grant execute on function public.request_transaction_reversal(
  uuid, text
) to authenticated;

grant execute on function public.approve_transaction(
  uuid
) to authenticated;

grant execute on function public.reject_transaction(
  uuid, text
) to authenticated;

grant execute on function public.get_transaction_summary()
to authenticated;

commit;
